'TGUI':
  - 'tgui/**'

'Звук':
  - '**/*.ogg'

'Изменение Карты':
  - '**/*.dmm'

'Инструменты':
  - '.gihub/workflows/**'
  - 'tools/**'

'Керберос':
  - '_maps/map_files220/stations/deltastation.dmm'

'Кибериада':
  - '_maps/map_files220/stations/boxstation.dmm'

'Цереброн':
  - '_maps/map_files220/stations/metastation.dmm'

'НЕ МОДУЛЬНО':
  - all: ['code/**']

'Спрайты':
  - '**/*.dmi'

'Требуется изменение конфига':
  - 'config/**'

'Документация':
  - '**/*.md'

'Частичная модульность':
  - all: ['code/**', modular_ss220/**]

'SQL':
  - 'SQL/**'
